// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOIrkYeC8uOAtVtzLNxslI-Jz0zfMO2JQ',
    appId: '1:131525740165:web:117affb5116e42de674bec',
    messagingSenderId: '131525740165',
    projectId: 'insta-app-51cc9',
    authDomain: 'insta-app-51cc9.firebaseapp.com',
    storageBucket: 'insta-app-51cc9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp92q95nnAbgNF3Xc6GkD8Tj4BzvdmhmE',
    appId: '1:131525740165:android:4f08e34b8c0256dc674bec',
    messagingSenderId: '131525740165',
    projectId: 'insta-app-51cc9',
    storageBucket: 'insta-app-51cc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBktzTuoz2VqubxWqaV1h0hofJRw7kyLJo',
    appId: '1:131525740165:ios:4fb4e5bcda75c1d3674bec',
    messagingSenderId: '131525740165',
    projectId: 'insta-app-51cc9',
    storageBucket: 'insta-app-51cc9.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBktzTuoz2VqubxWqaV1h0hofJRw7kyLJo',
    appId: '1:131525740165:ios:4fb4e5bcda75c1d3674bec',
    messagingSenderId: '131525740165',
    projectId: 'insta-app-51cc9',
    storageBucket: 'insta-app-51cc9.appspot.com',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOIrkYeC8uOAtVtzLNxslI-Jz0zfMO2JQ',
    appId: '1:131525740165:web:1ee1fe506e027b78674bec',
    messagingSenderId: '131525740165',
    projectId: 'insta-app-51cc9',
    authDomain: 'insta-app-51cc9.firebaseapp.com',
    storageBucket: 'insta-app-51cc9.appspot.com',
  );
}
